package types

const (
	PathV1Sign             = "/v1/sign"
	PathHealthz            = "/healthz"
	PathRoot               = "/"
	PathAssetsPrefix       = "/assets/"
	PathApp                = "/app"
	PathAppPrefix          = "/app/"
	PathAdmin              = "/admin"
	PathAdminPrefix        = "/admin/"
	PathAdminSnapshot      = "/admin/snapshot"
	PathAdminLeases        = "/admin/leases"
	PathAdminLeasesPrefix  = "/admin/leases/"
	PathAdminAuthChallenge = "/admin/auth/challenge"
	PathAdminAuthLogin     = "/admin/auth/login"
	PathAdminLogout        = "/admin/logout"
	PathAdminAuthStatus    = "/admin/auth/status"
	PathAdminApproval      = "/admin/settings/approval-mode"
	PathAdminLandingPage   = "/admin/settings/landing-page"
	PathAdminUDP           = "/admin/settings/udp"
	PathAdminTCPPort       = "/admin/settings/tcp-port"
	PathAdminIPsPrefix     = "/admin/ips/"
	PathInstallShell       = "/install.sh"
	PathInstallPowerShell  = "/install.ps1"
	PathInstallBinPrefix   = "/install/bin/"

	PathAgentPrefix        = "/v1/agent"
	PathAgentStatus        = PathAgentPrefix + "/status"
	PathAgentShutdown      = PathAgentPrefix + "/shutdown"
	PathAgentTunnels       = PathAgentPrefix + "/tunnels"
	PathAgentTunnelsPrefix = PathAgentPrefix + "/tunnels/"
	PathAgentAuthChallenge = PathAgentPrefix + "/auth/challenge"
	PathAgentAuthLogin     = PathAgentPrefix + "/auth/login"
	PathAgentAuthLogout    = PathAgentPrefix + "/auth/logout"
	PathAgentAuthStatus    = PathAgentPrefix + "/auth/status"

	PathTunnelStatus    = "/tunnel/status"
	PathThumbnailPrefix = "/thumbnail/"

	PathSDKPrefix            = "/sdk/"
	PathSDKDomain            = "/sdk/domain"
	PathSDKRegisterChallenge = "/sdk/register/challenge"
	PathSDKRegister          = "/sdk/register"
	PathSDKRenew             = "/sdk/renew"
	PathSDKUnregister        = "/sdk/unregister"
	PathSDKHop               = "/sdk/hop"
	PathSDKConnect           = "/sdk/connect"
	PathDiscovery            = "/discovery"
	PathDiscoveryAnnounce    = "/discovery/announce"
)
